/**
 * Build-time extract of the iptv-org index — the TV panel's live path.
 *
 * ## Why an extract and not a fetch
 *
 * MEASURED: `channels.json` is **1,274,245 bytes gzipped, 9.8 MB raw**, and
 * `streams.json` a further 548,960 gzipped. No amount of caching makes that a
 * per-view fetch. `scripts/extract-ucdp.mjs` already set the precedent for this
 * shape — it reduces 417,968 events at build time — and the same reasoning
 * applies: pull once, keep the fields the panel actually reads, ship a small
 * artefact.
 *
 * ## The blocklist is applied HERE, before bundling
 *
 * This is the part that matters legally rather than merely for weight.
 * `blocklist.json` lists **1,578 channels — 1,211 `dmca` and 367 `nsfw`** — and
 * the index does not apply it to itself: all 1,420 that still exist are present
 * in `channels.json`. Filtering at extract time means the excluded channels
 * **never reach the bundle at all**, so no runtime path can render one by
 * mistake and no future refactor can route around the filter.
 *
 * The parser keeps its own blocklist check regardless. Two guards for one rule
 * is not redundancy here: this one bounds what ships, that one bounds what
 * renders, and they fail independently.
 *
 *   npx tsx scripts/extract-iptv.mjs
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const API = 'https://iptv-org.github.io/api';
const HEADERS = { 'User-Agent': 'worldpulse/0.0 (https://github.com/0xmortuex/worldpulse) build-extract' };

async function get(name) {
  const res = await fetch(`${API}/${name}.json`, { headers: HEADERS, signal: AbortSignal.timeout(180_000) });
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
  return res.json();
}

const [channels, streams, blocklist] = await Promise.all([
  get('channels'),
  get('streams'),
  get('blocklist'),
]);

const blocked = new Map(blocklist.map((entry) => [entry.channel, entry.reason]));

/**
 * Only channels with a stream are kept.
 *
 * A channel the index lists with no stream is a real distinction the panel
 * draws — "listed but not watchable" — but 24,000 of them would dominate the
 * artefact to preserve a state the panel can express from a count. The count is
 * kept per country instead, so the disclosure survives without the rows.
 */
const streamByChannel = new Map();
for (const stream of streams) {
  if (!stream.channel || streamByChannel.has(stream.channel)) continue;
  streamByChannel.set(stream.channel, { url: stream.url, quality: stream.quality ?? null });
}

const kept = [];
const removed = { dmca: 0, nsfw: 0 };
const withoutStream = {};

for (const channel of channels) {
  const reason = blocked.get(channel.id);
  if (reason) {
    removed[reason] = (removed[reason] ?? 0) + 1;
    continue;
  }
  // `is_nsfw` is an independent flag from the blocklist's nsfw reason, and they
  // do not fully overlap. Both are honoured; neither implies the other.
  if (channel.is_nsfw) {
    removed.nsfw += 1;
    continue;
  }

  const stream = streamByChannel.get(channel.id);
  if (!stream) {
    withoutStream[channel.country] = (withoutStream[channel.country] ?? 0) + 1;
    continue;
  }

  kept.push({
    id: channel.id,
    name: channel.name,
    country: channel.country,
    categories: channel.categories ?? [],
    closed: channel.closed ?? null,
    url: stream.url,
    quality: stream.quality,
  });
}

const artefact = {
  $comment: [
    'GENERATED by scripts/extract-iptv.mjs — do not hand-edit.',
    '',
    'The live indexes are 9.8 MB and 3.3 MB raw, which is not a per-view fetch. This is the',
    'build-time reduction, per the extract-ucdp.mjs precedent.',
    '',
    'THE BLOCKLIST IS ALREADY APPLIED. Channels removed on copyright demand or flagged adult',
    'are not in this file at all, so no runtime path can render one. The parser keeps its own',
    'check as well: this bounds what ships, that bounds what renders, and they fail',
    'independently.',
    '',
    'Channels with no stream are counted per country rather than listed — the panel needs the',
    'COUNT to say "listed but not watchable", not the rows.',
  ],
  extractedOn: new Date().toISOString().slice(0, 10),
  removed,
  withoutStream,
  channels: kept,
};

const out = resolve(import.meta.dirname, '..', 'data', 'iptv-extract.json');
const json = `${JSON.stringify(artefact)}\n`;
writeFileSync(out, json);

console.log(`channels in:      ${channels.length}`);
console.log(`blocked/nsfw out: ${removed.dmca} dmca, ${removed.nsfw} nsfw`);
console.log(`no stream out:    ${Object.values(withoutStream).reduce((a, b) => a + b, 0)}`);
console.log(`kept:             ${kept.length}`);
console.log(`artefact:         ${(json.length / 1024).toFixed(1)} KB`);

/**
 * ## This artefact MUST NOT be a static import
 *
 * 1.8 MB against an app-chunk budget of 570 KB. Importing it at the top of a
 * module would put the whole TV catalogue in the initial bundle for every
 * visitor, including the ones who never open that tab — and the bundle budget
 * would fail the build, which is the guard working rather than an obstacle.
 *
 * The panel loads it with a dynamic `import()` when the tab is first opened, so
 * it is a separate chunk fetched on demand. That is the same reasoning as the
 * fetch it replaces, moved to build time: the point was never to avoid
 * transferring the data, it was to avoid transferring 9.8 MB of it and to apply
 * the blocklist before anyone could render what it excludes.
 */
if (json.length / 1024 > 3000) {
  console.error('\nartefact exceeded 3 MB — re-check what is being kept before shipping it');
  process.exitCode = 1;
}

/**
 * A blocked channel reaching the artefact is the one outcome that must stop the
 * build. It cannot happen given the loop above — which is exactly why it is
 * asserted: the guard costs nothing and the failure it prevents is legal.
 */
const leaked = kept.filter((channel) => blocked.has(channel.id));
if (leaked.length > 0) {
  console.error(`\n${leaked.length} blocklisted channel(s) reached the artefact: ${leaked.slice(0, 5).map((c) => c.id).join(', ')}`);
  process.exit(1);
}
